# Generated by Django 5.2.1 on 2025-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_type',
            field=models.CharField(choices=[('PU', 'Per Unit'), ('kg', 'kilogram'), ('g', 'gram'), ('lb', 'pound'), ('oz', 'ounce'), ('L', 'Liter'), ('ml', 'milliliter'), ('gal', 'gallon'), ('qt', 'quart'), ('pt', 'pint'), ('m', 'meter'), ('cm', 'centimeter'), ('mm', 'millimeter'), ('ft', 'feet'), ('in', 'inch')], default='PU', max_length=20),
        ),
    ]
