# Generated by Django 5.2.1 on 2025-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_price_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_type',
            new_name='unit_type',
        ),
        migrations.AddField(
            model_name='item',
            name='unit_amount',
            field=models.FloatField(default=1),
        ),
    ]
