# Generated by Django 5.2.1 on 2025-06-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rename_price_type_item_unit_type_item_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency_type',
            field=models.CharField(default='NOK', max_length=3),
        ),
    ]
