# Generated by Django 5.2.1 on 2025-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='base_price',
        ),
        migrations.CreateModel(
            name='StorePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='NOK', max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_prices', to='item.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_prices', to='item.store')),
            ],
            options={
                'unique_together': {('item', 'store')},
            },
        ),
    ]
